name: 'cache-action'
description: 'A Github Action that caches files to/from an S3 bucket.'
author: 'eric@hololabs.org'
inputs:
  should-restore:
    required: false
    description: If true, the action should attempt to restore data from the cache.  Default is true.
    default: 'true'
  should-save:
    required: false
    description: If true, the action should attempt to save data back to the cache.  Default is true.
    default: 'true'
  key:
    required: true
    description: The key used when writing data to the cache  
  path:
    required: true
    description: Repo-relative path to the directory to be cached
  restore-keys:
    required: false
    description: If provided, this is a prioritized list (one key per line) of cache keys to try when fetching the cache data
    default: ''
  s3-bucket-name:
    required: true
    description: Name of the s3 bucket in which cached files are stored
  s3-key-prefix:
    required: false
    description: The location within the bucket to store the cached files
    default: ''
  compression-level:
    required: false
    description: The zstd compression level to use.  Values range from '-4' to '19'.  Default is '3'.  '0' is equivalent to default.
    default: ''
  compression-threads:
    required: false
    description: The number of threads that zstd should use for compression.
    default: ''
outputs:
  cache-hit:
    description: A boolean value to indicate whether data was found in the cache
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: 'success()'
